# Generated by Django 2.2.7 on 2019-11-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profileImage',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
