# Generated by Django 2.2.7 on 2019-11-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_account_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profileImage',
            field=models.ImageField(upload_to='profile_images'),
        ),
    ]
