# Generated by Django 2.2.7 on 2019-11-17 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20191114_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='profileImage',
        ),
    ]
